// Hacker Green theme for Monaco Editor
export const hackerGreenDark = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: '00ff00', background: '000000' },
    { token: 'comment', foreground: '008800', fontStyle: 'italic' },
    { token: 'keyword', foreground: '00ff00', fontStyle: 'bold' },
    { token: 'operator', foreground: '00ff00' },
    { token: 'namespace', foreground: '00cc00' },
    { token: 'type', foreground: '00ff88' },
    { token: 'struct', foreground: '00ff88' },
    { token: 'class', foreground: '00ff88' },
    { token: 'interface', foreground: '00ff88' },
    { token: 'enum', foreground: '00ff88' },
    { token: 'typeParameter', foreground: '00ff88' },
    { token: 'function', foreground: '00ffcc' },
    { token: 'member', foreground: '00ffcc' },
    { token: 'macro', foreground: '00ffcc' },
    { token: 'variable', foreground: '88ff88' },
    { token: 'parameter', foreground: '88ff88' },
    { token: 'property', foreground: '88ff88' },
    { token: 'label', foreground: '88ff88' },
    { token: 'string', foreground: '66ff66' },
    { token: 'string.escape', foreground: '00ff00', fontStyle: 'bold' },
    { token: 'number', foreground: '00ff99' },
    { token: 'regexp', foreground: '00ffaa' },
    { token: 'delimiter', foreground: '00ff00' },
    { token: 'tag', foreground: '00ff00' },
    { token: 'annotation', foreground: '00cc00' },
    { token: 'decorator', foreground: '00cc00' },
    { token: 'attribute', foreground: '00ff88' },
    { token: 'constant', foreground: '00ff99', fontStyle: 'bold' },
    { token: 'identifier', foreground: '88ff88' },
  ],
  colors: {
    'editor.foreground': '#00FF00',
    'editor.background': '#000000',
    'editorCursor.foreground': '#00FF00',
    'editor.lineHighlightBackground': '#001100',
    'editorLineNumber.foreground': '#008800',
    'editorLineNumber.activeForeground': '#00FF00',
    'editor.selectionBackground': '#003300',
    'editor.inactiveSelectionBackground': '#002200',
    'editorIndentGuide.background': '#001100',
    'editorIndentGuide.activeBackground': '#003300',
    'editorWhitespace.foreground': '#002200',
    'editor.findMatchBackground': '#005500',
    'editor.findMatchHighlightBackground': '#003300',
    'editor.wordHighlightBackground': '#003300',
    'editor.wordHighlightStrongBackground': '#005500',
    'editorBracketMatch.background': '#003300',
    'editorBracketMatch.border': '#00FF00',
    'scrollbarSlider.background': '#00330066',
    'scrollbarSlider.hoverBackground': '#00550088',
    'scrollbarSlider.activeBackground': '#00FF0066',
  }
}

export const hackerGreenLight = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '006600', background: 'F5F5F5' },
    { token: 'comment', foreground: '00AA00', fontStyle: 'italic' },
    { token: 'keyword', foreground: '008800', fontStyle: 'bold' },
    { token: 'operator', foreground: '008800' },
    { token: 'namespace', foreground: '009900' },
    { token: 'type', foreground: '00AA00' },
    { token: 'struct', foreground: '00AA00' },
    { token: 'class', foreground: '00AA00' },
    { token: 'interface', foreground: '00AA00' },
    { token: 'enum', foreground: '00AA00' },
    { token: 'typeParameter', foreground: '00AA00' },
    { token: 'function', foreground: '00BB00' },
    { token: 'member', foreground: '00BB00' },
    { token: 'macro', foreground: '00BB00' },
    { token: 'variable', foreground: '008800' },
    { token: 'parameter', foreground: '008800' },
    { token: 'property', foreground: '008800' },
    { token: 'label', foreground: '008800' },
    { token: 'string', foreground: '00AA00' },
    { token: 'string.escape', foreground: '008800', fontStyle: 'bold' },
    { token: 'number', foreground: '00CC00' },
    { token: 'regexp', foreground: '00BB00' },
    { token: 'delimiter', foreground: '006600' },
    { token: 'tag', foreground: '008800' },
    { token: 'annotation', foreground: '009900' },
    { token: 'decorator', foreground: '009900' },
    { token: 'attribute', foreground: '00AA00' },
    { token: 'constant', foreground: '00CC00', fontStyle: 'bold' },
    { token: 'identifier', foreground: '006600' },
  ],
  colors: {
    'editor.foreground': '#006600',
    'editor.background': '#F5F5F5',
    'editorCursor.foreground': '#008800',
    'editor.lineHighlightBackground': '#E8F5E8',
    'editorLineNumber.foreground': '#00AA00',
    'editorLineNumber.activeForeground': '#008800',
    'editor.selectionBackground': '#C8E6C8',
    'editor.inactiveSelectionBackground': '#D8F0D8',
    'editorIndentGuide.background': '#E0F0E0',
    'editorIndentGuide.activeBackground': '#C0E0C0',
    'editorWhitespace.foreground': '#D0E8D0',
    'editor.findMatchBackground': '#A8D8A8',
    'editor.findMatchHighlightBackground': '#C8E6C8',
    'editor.wordHighlightBackground': '#C8E6C8',
    'editor.wordHighlightStrongBackground': '#A8D8A8',
    'editorBracketMatch.background': '#C8E6C8',
    'editorBracketMatch.border': '#008800',
    'scrollbarSlider.background': '#88CC8866',
    'scrollbarSlider.hoverBackground': '#66BB6688',
    'scrollbarSlider.activeBackground': '#44AA4466',
  }
}
